#!/bin/sh 

PATH=$HOME/.local/bin:$PATH # for rclonesync  
PATH=/usr/bin:$PATH # for notify-send 
eval "export $(egrep -z DBUS_SESSION_BUS_ADDRESS /proc/$(pgrep -u $LOGNAME gnome-session)/environ)"; # need to give a display for notify-send 

rclonesync $HOME/gdrive gdrive: --filters-file $HOME/scripts/gdrive_filter.txt --remove-empty-directories > /$HOME/logs/gdrive-sync.log 2>&1 

if [ $? -ne 0 ]; then
    notify-send -i face-crying  gdrive-sync "gdrive sync failed" --urgency=critical
fi

    
