#!/bin/bash 

read -p "Enter old branch: " old_branch
read -p "Enter new branch name: " new_branch
read -p "Push to origin? (y/n): " push_origin 

git branch -m $old_branch $new_branch

if [ "$push_origin" = "y" ]; then
    echo "pushing to origin"
    git push origin -u $new_branch 
    git push origin --delete $old_branch 
fi 



